// <auto-generated />
namespace URLShortener.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class users_admin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(users_admin));
        
        string IMigrationMetadata.Id
        {
            get { return "202311292033586_users_admin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
